Added Firebase id in User table
LukaDurisic/Tanprom-back pull request #11
Opened 2023-06-21 12:24 UTC by LukaDurisic

2023-06-21 12:34 UTC, franesitum requested changes

2023-06-21 12:34 UTC, franesitum commented on modules/models/User.js
> +    firebaseUID: DataTypes.STRING,
Ako koristis firebase za sve vrste logina (i email/password i third party) onda firebaseUID ne smi bit nullable, a moze (i ne mora) se koristit ko primary key user tablice, ovako imas dva identifikatora korisnika dok ti triba samo jedan

2023-06-21 12:34 UTC, franesitum commented on modules/data/userQuery.js
>      });
dodaj ili vracanje objekta novokreiranog korisnika ili potvrdu o uspjehu kreiranja korisnika za potvrdu uspjeha kreacije

2023-06-21 12:34 UTC, franesitum commented on modules/models/User.js
> +    password: DataTypes.STRING,
ako koristis firebase nema potrebe za spremanjem passworda u tvoju bazu podataka - cuva se na firebase-u jer je sigurnije i ima built-in funkcije za password reset

2023-06-21 12:34 UTC, franesitum commented on modules/data/userQuery.js
>        password: password,
sifru ne treba spremat (vidi komentar na user modelu), al ako ces je iz bilo kojeg razloga spremat obavezno treba bit hashirana

2023-07-01 14:24 UTC, merged

2023-07-01 14:35 UTC, franesitum commented
Kakvo je ovo ponasanje đaka mergea se na master bez odobrenja
sub, 1. srp 2023. u 16:24 Luka ***@***.***> napisao je:

> Merged #11 <https://github.com/LukaDurisic/Tanprom-back/pull/11> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LukaDurisic/Tanprom-back/pull/11#event-9696565693>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYUK772IBFKGJ2YS6GYW6MLXOAXLVANCNFSM6AAAAAAZOVMJHU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-07-01 14:43 UTC, LukaDurisic commented
Pa napravio sam šta je trebalo tamo a ti nikako da mergeaš onda eto haha

2023-07-01 14:46 UTC, franesitum commented
Bit ce sankcija

sub, 1. srp 2023. u 16:43 Luka ***@***.***> napisao je:

> Pa napravio sam šta je trebalo tamo a ti nikako da mergeaš onda eto haha
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LukaDurisic/Tanprom-back/pull/11#issuecomment-1615944432>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYUK77YWJFIRIITL5LWPX3LXOAZQZANCNFSM6AAAAAAZOVMJHU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>